#[derive(Debug, Clone, PartialEq, Eq)]
pub struct EnglishToken {
    pub kind: &'static str,
    pub reading: String,
    pub tts_text: String,
    pub source: &'static str,
    pub confidence: u8,
}

fn abbreviation_reading(token: &str) -> String {
    token
        .chars()
        .map(|ch| match ch {
            'A' => "エー",
            'B' => "ビー",
            'C' => "シー",
            'D' => "ディー",
            'E' => "イー",
            'F' => "エフ",
            'G' => "ジー",
            'H' => "エイチ",
            'I' => "アイ",
            'J' => "ジェー",
            'K' => "ケー",
            'L' => "エル",
            'M' => "エム",
            'N' => "エヌ",
            'O' => "オー",
            'P' => "ピー",
            'Q' => "キュー",
            'R' => "アール",
            'S' => "エス",
            'T' => "ティー",
            'U' => "ユー",
            'V' => "ブイ",
            'W' => "ダブリュー",
            'X' => "エックス",
            'Y' => "ワイ",
            'Z' => "ズィー",
            _ => "",
        })
        .collect()
}

pub fn classify_english_token(token: &str) -> EnglishToken {
    let lower = token.to_ascii_lowercase();

    // Tier 1: Abbreviation — all-uppercase ASCII tokens
    if token.chars().all(|c| c.is_ascii_uppercase()) {
        let reading = abbreviation_reading(token);
        return EnglishToken {
            kind: "abbreviation",
            reading: reading.clone(),
            tts_text: reading,
            source: "abbreviation",
            confidence: 100,
        };
    }

    // Tier 2: Built-in override — specific product/tech names
    let override_reading = match lower.as_str() {
        "react" => Some("リアクト"),
        "docker" => Some("ドッカー"),
        "github" => Some("ギットハブ"),
        "typescript" => Some("タイプスクリプト"),
        "javascript" => Some("ジャバスクリプト"),
        _ => None,
    };

    if let Some(reading) = override_reading {
        return EnglishToken {
            kind: "override",
            reading: reading.to_string(),
            tts_text: reading.to_string(),
            source: "override",
            confidence: 100,
        };
    }

    // Tier 3: Dictionary-corrected — common English→Japanese loanword readings
    let corrected_reading = dictionary_corrected_reading(&lower);
    if let Some(reading) = corrected_reading {
        return EnglishToken {
            kind: "dictionary_corrected",
            reading: reading.clone(),
            tts_text: reading,
            source: "dictionary_corrected",
            confidence: 85,
        };
    }

    // Tier 4: Unknown English — preserve original, no fabricated reading
    EnglishToken {
        kind: "unknown",
        reading: String::new(),
        tts_text: token.to_string(),
        source: "unknown_english",
        confidence: 0,
    }
}

fn dictionary_corrected_reading(lower: &str) -> Option<String> {
    match lower {
        "server" => Some("サーバー"),
        "browser" => Some("ブラウザ"),
        "client" => Some("クライアント"),
        "internet" => Some("インターネット"),
        "computer" => Some("コンピューター"),
        "program" => Some("プログラム"),
        "system" => Some("システム"),
        "data" => Some("データ"),
        "file" => Some("ファイル"),
        "text" => Some("テキスト"),
        "image" => Some("イメージ"),
        "audio" => Some("オーディオ"),
        "video" => Some("ビデオ"),
        "network" => Some("ネットワーク"),
        "software" => Some("ソフトウェア"),
        "hardware" => Some("ハードウェア"),
        "database" => Some("データベース"),
        "interface" => Some("インターフェース"),
        "protocol" => Some("プロトコル"),
        "service" => Some("サービス"),
        "application" => Some("アプリケーション"),
        "document" => Some("ドキュメント"),
        "project" => Some("プロジェクト"),
        "version" => Some("バージョン"),
        "config" => Some("コンフィグ"),
        "default" => Some("デフォルト"),
        "window" => Some("ウィンドウ"),
        "screen" => Some("スクリーン"),
        "display" => Some("ディスプレイ"),
        "message" => Some("メッセージ"),
        "error" => Some("エラー"),
        "command" => Some("コマンド"),
        "option" => Some("オプション"),
        "code" => Some("コード"),
        "source" => Some("ソース"),
        "build" => Some("ビルド"),
        "debug" => Some("デバッグ"),
        "test" => Some("テスト"),
        "cache" => Some("キャッシュ"),
        "memory" => Some("メモリー"),
        "storage" => Some("ストレージ"),
        "buffer" => Some("バッファ"),
        "thread" => Some("スレッド"),
        "process" => Some("プロセス"),
        "request" => Some("リクエスト"),
        "response" => Some("レスポンス"),
        "plugin" => Some("プラグイン"),
        "module" => Some("モジュール"),
        "package" => Some("パッケージ"),
        "library" => Some("ライブラリ"),
        "framework" => Some("フレームワーク"),
        "template" => Some("テンプレート"),
        "component" => Some("コンポーネント"),
        "container" => Some("コンテナ"),
        "instance" => Some("インスタンス"),
        "object" => Some("オブジェクト"),
        "class" => Some("クラス"),
        "method" => Some("メソッド"),
        "function" => Some("ファンクション"),
        "variable" => Some("バリアブル"),
        "property" => Some("プロパティ"),
        "element" => Some("エレメント"),
        "pattern" => Some("パターン"),
        "design" => Some("デザイン"),
        "style" => Some("スタイル"),
        "layout" => Some("レイアウト"),
        "color" => Some("カラー"),
        "theme" => Some("テーマ"),
        "icon" => Some("アイコン"),
        "button" => Some("ボタン"),
        "menu" => Some("メニュー"),
        "dialog" => Some("ダイアログ"),
        "panel" => Some("パネル"),
        "toolbar" => Some("ツールバー"),
        "sidebar" => Some("サイドバー"),
        "header" => Some("ヘッダー"),
        "footer" => Some("フッター"),
        "title" => Some("タイトル"),
        "content" => Some("コンテンツ"),
        "format" => Some("フォーマット"),
        "filter" => Some("フィルター"),
        "export" => Some("エクスポート"),
        "import" => Some("インポート"),
        "upload" => Some("アップロード"),
        "download" => Some("ダウンロード"),
        "install" => Some("インストール"),
        "update" => Some("アップデート"),
        "upgrade" => Some("アップグレード"),
        "backup" => Some("バックアップ"),
        "restore" => Some("リストア"),
        "login" => Some("ログイン"),
        "logout" => Some("ログアウト"),
        "profile" => Some("プロフィール"),
        "account" => Some("アカウント"),
        "password" => Some("パスワード"),
        "token" => Some("トークン"),
        "vintage" => Some("ビンテージ"),
        "web" => Some("ウェブ"),
        "site" => Some("サイト"),
        "page" => Some("ページ"),
        "link" => Some("リンク"),
        "search" => Some("サーチ"),
        "index" => Some("インデックス"),
        "query" => Some("クエリ"),
        "result" => Some("リザルト"),
        "status" => Some("ステータス"),
        "mode" => Some("モード"),
        "type" => Some("タイプ"),
        "value" => Some("バリュー"),
        "key" => Some("キー"),
        "name" => Some("ネーム"),
        "address" => Some("アドレス"),
        "email" => Some("メール"),
        "phone" => Some("フォン"),
        "number" => Some("ナンバー"),
        "date" => Some("デート"),
        "time" => Some("タイム"),
        "size" => Some("サイズ"),
        "level" => Some("レベル"),
        "range" => Some("レンジ"),
        "limit" => Some("リミット"),
        "offset" => Some("オフセット"),
        "section" => Some("セクション"),
        "category" => Some("カテゴリー"),
        "group" => Some("グループ"),
        "user" => Some("ユーザー"),
        "admin" => Some("アドミン"),
        "owner" => Some("オーナー"),
        "member" => Some("メンバー"),
        "role" => Some("ロール"),
        "permission" => Some("パーミッション"),
        "access" => Some("アクセス"),
        "action" => Some("アクション"),
        "event" => Some("イベント"),
        "task" => Some("タスク"),
        "job" => Some("ジョブ"),
        "queue" => Some("キュー"),
        "worker" => Some("ワーカー"),
        "agent" => Some("エージェント"),
        "model" => Some("モデル"),
        "engine" => Some("エンジン"),
        "driver" => Some("ドライバー"),
        "layer" => Some("レイヤー"),
        "stack" => Some("スタック"),
        "stream" => Some("ストリーム"),
        "channel" => Some("チャンネル"),
        "signal" => Some("シグナル"),
        "handler" => Some("ハンドラー"),
        "listener" => Some("リスナー"),
        "callback" => Some("コールバック"),
        "middleware" => Some("ミドルウェア"),
        "router" => Some("ルーター"),
        "gateway" => Some("ゲートウェイ"),
        "proxy" => Some("プロキシ"),
        "domain" => Some("ドメイン"),
        "host" => Some("ホスト"),
        "port" => Some("ポート"),
        "socket" => Some("ソケット"),
        "session" => Some("セッション"),
        "cookie" => Some("クッキー"),
        "payload" => Some("ペイロード"),
        "schema" => Some("スキーマ"),
        "migration" => Some("マイグレーション"),
        "transaction" => Some("トランザクション"),
        "commit" => Some("コミット"),
        "rollback" => Some("ロールバック"),
        "branch" => Some("ブランチ"),
        "merge" => Some("マージ"),
        "patch" => Some("パッチ"),
        "release" => Some("リリース"),
        "deploy" => Some("デプロイ"),
        "pipeline" => Some("パイプライン"),
        "cluster" => Some("クラスター"),
        "node" => Some("ノード"),
        "pod" => Some("ポッド"),
        "cloud" => Some("クラウド"),
        "virtual" => Some("バーチャル"),
        _ => None,
    }
    .map(|s| s.to_string())
}
